# -*- coding: utf-8 -*-
"""
Created on Sun Feb 26 00:46:37 2017

@author: Crissy
"""

#%%
#Phase Diagram for different k2 and r values
plt.figure()
plt.scatter(.7,.01, marker='o', label = "oscillations")
plt.scatter(1.4,.05, marker='o')
plt.scatter(2.0,.1, marker='o')
plt.scatter(0.5,0.001, marker='o')
plt.scatter(1.0,0.001, marker='o')
plt.scatter(1.5,0.001, marker='o')
plt.scatter(2.0,0.001, marker='o')
plt.scatter(2.5,0.001, marker='o')
plt.scatter(0.5,.2, marker='o')
plt.scatter(1.0,.2, marker='o')
plt.scatter(1.5,.2, marker='o')
plt.scatter(2.0,.2, marker='o')
plt.scatter(0.5,.6, marker='o')
plt.scatter(1.0,.6, marker='o')
plt.scatter(2.5,.6, marker='o')
plt.scatter(0.5,.8, marker='o')
plt.scatter(.007,.001, marker='x', label = "no oscillations")
plt.scatter(.07,.005, marker='x')
plt.scatter(2.5,.5, marker='x')
plt.scatter(3.0,1.0, marker='x')
plt.scatter(0.007,0.2, marker='x')
plt.scatter(2.5,0.2, marker='x')
plt.scatter(0.007,0.4, marker='x')
plt.scatter(0.5,0.4, marker='x')
plt.scatter(1.0,0.4, marker='x')
plt.scatter(1.5,0.4, marker='x')
plt.scatter(2.0,0.4, marker='x')
plt.scatter(2.5,0.4, marker='x')
plt.scatter(0.007,0.6, marker='x')
plt.scatter(1.5,0.6, marker='x')
plt.scatter(2.0,0.6, marker='x')
plt.scatter(0.007,0.8, marker='x')
plt.scatter(1.0,0.8, marker='x')
plt.scatter(1.5,0.8, marker='x')
plt.scatter(2.0,0.8, marker='x')
plt.scatter(2.5,0.8, marker='x')
plt.legend()
plt.xlabel('r Value', size=12)
plt.ylabel('k2 Value', size=12)
plt.title('Phase Diagram for Lotka-Volterra Predator-Prey System', size=14)



#%%
#More Graphs and Phase Portraits
#k2=.001, r=.5
xe, ye, Vectordxdt, Vectordydt = Phase_Portrait(k1, 0.001, d1, d2, 0.5, y0)
plt.subplot(2,4,1)
plt.quiver(xe, ye, Vectordxdt, Vectordydt)
plt.title('Phase Portrait for the Lotka-Volterra predator-prey system with k2=0.001 & r=0.5', size=8)
plt.xlabel('Predator', size=12)
plt.ylabel('Prey', size=12)
plt.streamplot(xe, ye, Vectordxdt, Vectordydt)
plt.xlim(0,50)
plt.ylim(0,50)
t, X_odeint = Odeint(k1, 0.001, d1, d2, 0.5, y0, xi, yi, Ti, Tf, dt)
plt.subplot(2,4,5)
plt.plot(t,X_odeint)
plt.legend(["Predator", "Prey"])
plt.xlabel('Time', size=12)
plt.ylabel('Population', size=12)
plt.title('Lotka-Volterra predator-prey system with k2=0.001 & r=0.5', size=10)
#k2=.001, r = 1
xe, ye, Vectordxdt, Vectordydt = Phase_Portrait(k1, 0.001, d1, d2, 1.0, y0)
plt.subplot(2,4,2)
plt.quiver(xe, ye, Vectordxdt, Vectordydt)
plt.title('Phase Portrait for the Lotka-Volterra predator-prey system with k2=0.001 & r=1.0', size=8)
plt.xlabel('Predator', size=12)
plt.ylabel('Prey', size=12)
plt.streamplot(xe, ye, Vectordxdt, Vectordydt)
plt.xlim(0,50)
plt.ylim(0,50)
t, X_odeint = Odeint(k1, 0.001, d1, d2, 1.0, y0, xi, yi, Ti, Tf, dt)
plt.subplot(2,4,6)
plt.plot(t,X_odeint)
plt.legend(["Predator", "Prey"])
plt.xlabel('Time', size=12)
plt.ylabel('Population', size=12)
plt.title('Lotka-Volterra predator-prey system with k2=0.001 & r=1.0', size=10)
#k2=.001, r = 1.5
xe, ye, Vectordxdt, Vectordydt = Phase_Portrait(k1, 0.001, d1, d2, 1.5, y0)
plt.subplot(2,4,3)
plt.quiver(xe, ye, Vectordxdt, Vectordydt)
plt.title('Phase Portrait for the Lotka-Volterra predator-prey system with k2=0.001 & r=1.5', size=8)
plt.xlabel('Predator', size=12)
plt.ylabel('Prey', size=12)
plt.streamplot(xe, ye, Vectordxdt, Vectordydt)
plt.xlim(0,50)
plt.ylim(0,50)
t, X_odeint = Odeint(k1, 0.001, d1, d2, 1.5, y0, xi, yi, Ti, Tf, dt)
plt.subplot(2,4,7)
plt.plot(t,X_odeint)
plt.legend(["Predator", "Prey"])
plt.xlabel('Time', size=12)
plt.ylabel('Population', size=12)
plt.title('Lotka-Volterra predator-prey system with k2=0.001 & r=1.5', size=10)
#k2=.001, r = 2
xe, ye, Vectordxdt, Vectordydt = Phase_Portrait(k1, 0.001, d1, d2, 2.0, y0)
plt.subplot(2,4,4)
plt.quiver(xe, ye, Vectordxdt, Vectordydt)
plt.title('Phase Portrait for the Lotka-Volterra predator-prey system with k2=0.001 & r=2.0', size=8)
plt.xlabel('Predator', size=12)
plt.ylabel('Prey', size=12)
plt.streamplot(xe, ye, Vectordxdt, Vectordydt)
plt.xlim(0,50)
plt.ylim(0,50)
t, X_odeint = Odeint(k1, 0.001, d1, d2, 2.0, y0, xi, yi, Ti, Tf, dt)
plt.subplot(2,4,8)
plt.plot(t,X_odeint)
plt.legend(["Predator", "Prey"])
plt.xlabel('Time', size=12)
plt.ylabel('Population', size=12)
plt.title('Lotka-Volterra predator-prey system with k2=0.001 & r=2.0', size=10)

#%%
#k2=.001, r = 2.5
xe, ye, Vectordxdt, Vectordydt = Phase_Portrait(k1, 0.001, d1, d2, 2.5, y0)
plt.subplot(2,4,1)
plt.quiver(xe, ye, Vectordxdt, Vectordydt)
plt.title('Phase Portrait for the Lotka-Volterra predator-prey system with k2=0.001 & r=2.5', size=8)
plt.xlabel('Predator', size=12)
plt.ylabel('Prey', size=12)
plt.streamplot(xe, ye, Vectordxdt, Vectordydt)
plt.xlim(0,50)
plt.ylim(0,50)
t, X_odeint = Odeint(k1, 0.001, d1, d2, 2.5, y0, xi, yi, Ti, Tf, dt)
plt.subplot(2,4,5)
plt.plot(t,X_odeint)
plt.legend(["Predator", "Prey"])
plt.xlabel('Time', size=12)
plt.ylabel('Population', size=12)
plt.title('Lotka-Volterra predator-prey system with k2=0.001 & r=2.5', size=10)
#k2=.2, r = 0.007
xe, ye, Vectordxdt, Vectordydt = Phase_Portrait(k1, 0.2, d1, d2, 0.007, y0)
plt.subplot(2,4,2)
plt.quiver(xe, ye, Vectordxdt, Vectordydt)
plt.title('Phase Portrait for the Lotka-Volterra predator-prey system with k2=0.2 & r=0.007', size=8)
plt.xlabel('Predator', size=12)
plt.ylabel('Prey', size=12)
plt.streamplot(xe, ye, Vectordxdt, Vectordydt)
plt.xlim(0,50)
plt.ylim(0,50)
t, X_odeint = Odeint(k1, 0.2, d1, d2, 0.007, y0, xi, yi, Ti, Tf, dt)
plt.subplot(2,4,6)
plt.plot(t,X_odeint)
plt.legend(["Predator", "Prey"])
plt.xlabel('Time', size=12)
plt.ylabel('Population', size=12)
plt.title('Lotka-Volterra predator-prey system with k2=0.2 & r=0.007', size=10)
#k2=.2, r=0.5
xe, ye, Vectordxdt, Vectordydt = Phase_Portrait(k1, 0.2, d1, d2, 0.5, y0)
plt.subplot(2,4,3)
plt.quiver(xe, ye, Vectordxdt, Vectordydt)
plt.title('Phase Portrait for the Lotka-Volterra predator-prey system with k2=0.2 & r=0.5', size=8)
plt.xlabel('Predator', size=12)
plt.ylabel('Prey', size=12)
plt.streamplot(xe, ye, Vectordxdt, Vectordydt)
plt.xlim(0,50)
plt.ylim(0,50)
t, X_odeint = Odeint(k1, 0.2, d1, d2, 0.5, y0, xi, yi, Ti, Tf, dt)
plt.subplot(2,4,7)
plt.plot(t,X_odeint)
plt.legend(["Predator", "Prey"])
plt.xlabel('Time', size=12)
plt.ylabel('Population', size=12)
plt.title('Lotka-Volterra predator-prey system with k2=0.2 & r=0.5', size=10)
#k2=.2, r = 1.0
xe, ye, Vectordxdt, Vectordydt = Phase_Portrait(k1, 0.2, d1, d2, 1.0, y0)
plt.subplot(2,4,4)
plt.quiver(xe, ye, Vectordxdt, Vectordydt)
plt.title('Phase Portrait for the Lotka-Volterra predator-prey system with k2=0.2 & r=1.0', size=8)
plt.xlabel('Predator', size=12)
plt.ylabel('Prey', size=12)
plt.streamplot(xe, ye, Vectordxdt, Vectordydt)
plt.xlim(0,50)
plt.ylim(0,50)
t, X_odeint = Odeint(k1, 0.2, d1, d2, 1.0, y0, xi, yi, Ti, Tf, dt)
plt.subplot(2,4,8)
plt.plot(t,X_odeint)
plt.legend(["Predator", "Prey"])
plt.xlabel('Time', size=12)
plt.ylabel('Population', size=12)
plt.title('Lotka-Volterra predator-prey system with k2=0.2 & r=1.0', size=10)
#%%
#k2=.2, r = 1.5
xe, ye, Vectordxdt, Vectordydt = Phase_Portrait(k1, 0.2, d1, d2, 1.5, y0)
plt.subplot(2,4,1)
plt.quiver(xe, ye, Vectordxdt, Vectordydt)
plt.title('Phase Portrait for the Lotka-Volterra predator-prey system with k2=0.2 & r=1.5', size=8)
plt.xlabel('Predator', size=12)
plt.ylabel('Prey', size=12)
plt.streamplot(xe, ye, Vectordxdt, Vectordydt)
plt.xlim(0,50)
plt.ylim(0,50)
t, X_odeint = Odeint(k1, 0.2, d1, d2, 1.5, y0, xi, yi, Ti, Tf, dt)
plt.subplot(2,4,5)
plt.plot(t,X_odeint)
plt.legend(["Predator", "Prey"])
plt.xlabel('Time', size=12)
plt.ylabel('Population', size=12)
plt.title('Lotka-Volterra predator-prey system with k2=0.2 & r=1.5', size=10)
#k2=.2, r = 2
xe, ye, Vectordxdt, Vectordydt = Phase_Portrait(k1, 0.2, d1, d2, 2.0, y0)
plt.subplot(2,4,2)
plt.quiver(xe, ye, Vectordxdt, Vectordydt)
plt.title('Phase Portrait for the Lotka-Volterra predator-prey system with k2=0.2 & r=2.0', size=8)
plt.xlabel('Predator', size=12)
plt.ylabel('Prey', size=12)
plt.streamplot(xe, ye, Vectordxdt, Vectordydt)
plt.xlim(0,50)
plt.ylim(0,50)
t, X_odeint = Odeint(k1, 0.2, d1, d2, 2.0, y0, xi, yi, Ti, Tf, dt)
plt.subplot(2,4,6)
plt.plot(t,X_odeint)
plt.legend(["Predator", "Prey"])
plt.xlabel('Time', size=12)
plt.ylabel('Population', size=12)
plt.title('Lotka-Volterra predator-prey system with k2=0.2 & r=2.0', size=10)
#k2=.2, r = 2.5
xe, ye, Vectordxdt, Vectordydt = Phase_Portrait(k1, 0.2, d1, d2, 2.5, y0)
plt.subplot(2,4,3)
plt.quiver(xe, ye, Vectordxdt, Vectordydt)
plt.title('Phase Portrait for the Lotka-Volterra predator-prey system with k2=0.2 & r=2.5', size=8)
plt.xlabel('Predator', size=12)
plt.ylabel('Prey', size=12)
plt.streamplot(xe, ye, Vectordxdt, Vectordydt)
plt.xlim(0,50)
plt.ylim(0,50)
t, X_odeint = Odeint(k1, 0.2, d1, d2, 2.5, y0, xi, yi, Ti, Tf, dt)
plt.subplot(2,4,7)
plt.plot(t,X_odeint)
plt.legend(["Predator", "Prey"])
plt.xlabel('Time', size=12)
plt.ylabel('Population', size=12)
plt.title('Lotka-Volterra predator-prey system with k2=0.2 & r=2.5', size=10)
#k2=.4, r=.007
xe, ye, Vectordxdt, Vectordydt = Phase_Portrait(k1, 0.4, d1, d2, 0.007, y0)
plt.subplot(2,4,4)
plt.quiver(xe, ye, Vectordxdt, Vectordydt)
plt.title('Phase Portrait for the Lotka-Volterra predator-prey system with k2=0.4 & r=0.007', size=8)
plt.xlabel('Predator', size=12)
plt.ylabel('Prey', size=12)
plt.streamplot(xe, ye, Vectordxdt, Vectordydt)
plt.xlim(0,50)
plt.ylim(0,50)
t, X_odeint = Odeint(k1, 0.4, d1, d2, 0.007, y0, xi, yi, Ti, Tf, dt)
plt.subplot(2,4,8)
plt.plot(t,X_odeint)
plt.legend(["Predator", "Prey"])
plt.xlabel('Time', size=12)
plt.ylabel('Population', size=12)
plt.title('Lotka-Volterra predator-prey system with k2=0.4 & r=0.007', size=10)

#%%
#k2=.4, r = .5
xe, ye, Vectordxdt, Vectordydt = Phase_Portrait(k1, 0.4, d1, d2, 0.5, y0)
plt.subplot(2,4,1)
plt.quiver(xe, ye, Vectordxdt, Vectordydt)
plt.title('Phase Portrait for the Lotka-Volterra predator-prey system with k2=0.4 & r=0.5', size=8)
plt.xlabel('Predator', size=12)
plt.ylabel('Prey', size=12)
plt.streamplot(xe, ye, Vectordxdt, Vectordydt)
plt.xlim(0,50)
plt.ylim(0,50)
t, X_odeint = Odeint(k1, 0.4, d1, d2, 0.5, y0, xi, yi, Ti, Tf, dt)
plt.subplot(2,4,5)
plt.plot(t,X_odeint)
plt.legend(["Predator", "Prey"])
plt.xlabel('Time', size=12)
plt.ylabel('Population', size=12)
plt.title('Lotka-Volterra predator-prey system with k2=0.4 & r=0.5', size=10)
#k2=.4, r = 1
xe, ye, Vectordxdt, Vectordydt = Phase_Portrait(k1, 0.4, d1, d2, 1.0, y0)
plt.subplot(2,4,2)
plt.quiver(xe, ye, Vectordxdt, Vectordydt)
plt.title('Phase Portrait for the Lotka-Volterra predator-prey system with k2=0.4 & r=1.0', size=8)
plt.xlabel('Predator', size=12)
plt.ylabel('Prey', size=12)
plt.streamplot(xe, ye, Vectordxdt, Vectordydt)
plt.xlim(0,50)
plt.ylim(0,50)
t, X_odeint = Odeint(k1, 0.4, d1, d2, 1.0, y0, xi, yi, Ti, Tf, dt)
plt.subplot(2,4,6)
plt.plot(t,X_odeint)
plt.legend(["Predator", "Prey"])
plt.xlabel('Time', size=12)
plt.ylabel('Population', size=12)
plt.title('Lotka-Volterra predator-prey system with k2=0.4 & r=1.0', size=10)
#k2=.4, r = 1.5
xe, ye, Vectordxdt, Vectordydt = Phase_Portrait(k1, 0.4, d1, d2, 1.5, y0)
plt.subplot(2,4,3)
plt.quiver(xe, ye, Vectordxdt, Vectordydt)
plt.title('Phase Portrait for the Lotka-Volterra predator-prey system with k2=0.4 & r=1.5', size=8)
plt.xlabel('Predator', size=12)
plt.ylabel('Prey', size=12)
plt.streamplot(xe, ye, Vectordxdt, Vectordydt)
plt.xlim(0,50)
plt.ylim(0,50)
t, X_odeint = Odeint(k1, 0.4, d1, d2, 1.5, y0, xi, yi, Ti, Tf, dt)
plt.subplot(2,4,7)
plt.plot(t,X_odeint)
plt.legend(["Predator", "Prey"])
plt.xlabel('Time', size=12)
plt.ylabel('Population', size=12)
plt.title('Lotka-Volterra predator-prey system with k2=0.4 & r=1.5', size=10)
#k2=.4, r=2
xe, ye, Vectordxdt, Vectordydt = Phase_Portrait(k1, 0.4, d1, d2, 2.0, y0)
plt.subplot(2,4,4)
plt.quiver(xe, ye, Vectordxdt, Vectordydt)
plt.title('Phase Portrait for the Lotka-Volterra predator-prey system with k2=0.4 & r=2.0', size=8)
plt.xlabel('Predator', size=12)
plt.ylabel('Prey', size=12)
plt.streamplot(xe, ye, Vectordxdt, Vectordydt)
plt.xlim(0,50)
plt.ylim(0,50)
t, X_odeint = Odeint(k1, 0.4, d1, d2, 2.0, y0, xi, yi, Ti, Tf, dt)
plt.subplot(2,4,8)
plt.plot(t,X_odeint)
plt.legend(["Predator", "Prey"])
plt.xlabel('Time', size=12)
plt.ylabel('Population', size=12)
plt.title('Lotka-Volterra predator-prey system with k2=0.4 & r=2.0', size=10)

#%%
#k2=.4, r = 2.5
xe, ye, Vectordxdt, Vectordydt = Phase_Portrait(k1, 0.4, d1, d2, 2.5, y0)
plt.subplot(2,4,1)
plt.quiver(xe, ye, Vectordxdt, Vectordydt)
plt.title('Phase Portrait for the Lotka-Volterra predator-prey system with k2=0.4 & r=2.5', size=8)
plt.xlabel('Predator', size=12)
plt.ylabel('Prey', size=12)
plt.streamplot(xe, ye, Vectordxdt, Vectordydt)
plt.xlim(0,50)
plt.ylim(0,50)
t, X_odeint = Odeint(k1, 0.4, d1, d2, 2.5, y0, xi, yi, Ti, Tf, dt)
plt.subplot(2,4,5)
plt.plot(t,X_odeint)
plt.legend(["Predator", "Prey"])
plt.xlabel('Time', size=12)
plt.ylabel('Population', size=12)
plt.title('Lotka-Volterra predator-prey system with k2=0.4 & r=2.5', size=10)
#k2=.6, r = 0.007
xe, ye, Vectordxdt, Vectordydt = Phase_Portrait(k1, 0.6, d1, d2, 0.007, y0)
plt.subplot(2,4,2)
plt.quiver(xe, ye, Vectordxdt, Vectordydt)
plt.title('Phase Portrait for the Lotka-Volterra predator-prey system with k2=0.6 & r=0.007', size=8)
plt.xlabel('Predator', size=12)
plt.ylabel('Prey', size=12)
plt.streamplot(xe, ye, Vectordxdt, Vectordydt)
plt.xlim(0,50)
plt.ylim(0,50)
t, X_odeint = Odeint(k1, 0.6, d1, d2, 0.007, y0, xi, yi, Ti, Tf, dt)
plt.subplot(2,4,6)
plt.plot(t,X_odeint)
plt.legend(["Predator", "Prey"])
plt.xlabel('Time', size=12)
plt.ylabel('Population', size=12)
plt.title('Lotka-Volterra predator-prey system with k2=0.6 & r=0.007', size=10)
#k2=.6, r = .5
xe, ye, Vectordxdt, Vectordydt = Phase_Portrait(k1, 0.6, d1, d2, 0.5, y0)
plt.subplot(2,4,3)
plt.quiver(xe, ye, Vectordxdt, Vectordydt)
plt.title('Phase Portrait for the Lotka-Volterra predator-prey system with k2=0.6 & r=0.5', size=8)
plt.xlabel('Predator', size=12)
plt.ylabel('Prey', size=12)
plt.streamplot(xe, ye, Vectordxdt, Vectordydt)
plt.xlim(0,50)
plt.ylim(0,50)
t, X_odeint = Odeint(k1, 0.6, d1, d2, 0.5, y0, xi, yi, Ti, Tf, dt)
plt.subplot(2,4,7)
plt.plot(t,X_odeint)
plt.legend(["Predator", "Prey"])
plt.xlabel('Time', size=12)
plt.ylabel('Population', size=12)
plt.title('Lotka-Volterra predator-prey system with k2=.6 & r=0.5', size=10)
#k2=.6, r=1
xe, ye, Vectordxdt, Vectordydt = Phase_Portrait(k1, 0.6, d1, d2, 1.0, y0)
plt.subplot(2,4,4)
plt.quiver(xe, ye, Vectordxdt, Vectordydt)
plt.title('Phase Portrait for the Lotka-Volterra predator-prey system with k2=0.6 & r=1.0', size=8)
plt.xlabel('Predator', size=12)
plt.ylabel('Prey', size=12)
plt.streamplot(xe, ye, Vectordxdt, Vectordydt)
plt.xlim(0,50)
plt.ylim(0,50)
t, X_odeint = Odeint(k1, 0.6, d1, d2, 1.0, y0, xi, yi, Ti, Tf, dt)
plt.subplot(2,4,8)
plt.plot(t,X_odeint)
plt.legend(["Predator", "Prey"])
plt.xlabel('Time', size=12)
plt.ylabel('Population', size=12)
plt.title('Lotka-Volterra predator-prey system with k2=0.6 & r=1.0', size=10)

#%%
#k2=.6, r = 1.5
xe, ye, Vectordxdt, Vectordydt = Phase_Portrait(k1, 0.6, d1, d2, 1.5, y0)
plt.subplot(2,4,1)
plt.quiver(xe, ye, Vectordxdt, Vectordydt)
plt.title('Phase Portrait for the Lotka-Volterra predator-prey system with k2=0.6 & r=1.5', size=8)
plt.xlabel('Predator', size=12)
plt.ylabel('Prey', size=12)
plt.streamplot(xe, ye, Vectordxdt, Vectordydt)
plt.xlim(0,50)
plt.ylim(0,50)
t, X_odeint = Odeint(k1, 0.6, d1, d2, 1.5, y0, xi, yi, Ti, Tf, dt)
plt.subplot(2,4,5)
plt.plot(t,X_odeint)
plt.legend(["Predator", "Prey"])
plt.xlabel('Time', size=12)
plt.ylabel('Population', size=12)
plt.title('Lotka-Volterra predator-prey system with k2=0.6 & r=1.5', size=10)
#k2=.6, r = 2
xe, ye, Vectordxdt, Vectordydt = Phase_Portrait(k1, 0.6, d1, d2, 2.0, y0)
plt.subplot(2,4,2)
plt.quiver(xe, ye, Vectordxdt, Vectordydt)
plt.title('Phase Portrait for the Lotka-Volterra predator-prey system with k2=0.6 & r=2.0', size=8)
plt.xlabel('Predator', size=12)
plt.ylabel('Prey', size=12)
plt.streamplot(xe, ye, Vectordxdt, Vectordydt)
plt.xlim(0,50)
plt.ylim(0,50)
t, X_odeint = Odeint(k1, 0.6, d1, d2, 2.0, y0, xi, yi, Ti, Tf, dt)
plt.subplot(2,4,6)
plt.plot(t,X_odeint)
plt.legend(["Predator", "Prey"])
plt.xlabel('Time', size=12)
plt.ylabel('Population', size=12)
plt.title('Lotka-Volterra predator-prey system with k2=0.6 & r=2.0', size=10)
#%%
#k2=.6, r = 2.5
xe, ye, Vectordxdt, Vectordydt = Phase_Portrait(k1, 0.6, d1, d2, 2.5, y0)
plt.subplot(2,4,3)
plt.quiver(xe, ye, Vectordxdt, Vectordydt)
plt.title('Phase Portrait for the Lotka-Volterra predator-prey system with k2=0.6 & r=2.5', size=8)
plt.xlabel('Predator', size=12)
plt.ylabel('Prey', size=12)
plt.streamplot(xe, ye, Vectordxdt, Vectordydt)
plt.xlim(0,50)
plt.ylim(0,50)
t, X_odeint = Odeint(k1, 0.6, d1, d2, 2.5, y0, xi, yi, Ti, Tf, dt)
plt.subplot(2,4,7)
plt.plot(t,X_odeint)
plt.legend(["Predator", "Prey"])
plt.xlabel('Time', size=12)
plt.ylabel('Population', size=12)
plt.title('Lotka-Volterra predator-prey system with k2=0.6 & r=2.5', size=10)
#%%
#k2=.8, r=.007
xe, ye, Vectordxdt, Vectordydt = Phase_Portrait(k1, 0.8, d1, d2, 0.007, y0)
plt.subplot(2,4,4)
plt.quiver(xe, ye, Vectordxdt, Vectordydt)
plt.title('Phase Portrait for the Lotka-Volterra predator-prey system with k2=0.8 & r=0.007', size=8)
plt.xlabel('Predator', size=12)
plt.ylabel('Prey', size=12)
plt.streamplot(xe, ye, Vectordxdt, Vectordydt)
plt.xlim(0,50)
plt.ylim(0,50)
t, X_odeint = Odeint(k1, 0.8, d1, d2, 0.007, y0, xi, yi, Ti, Tf, dt)
plt.subplot(2,4,8)
plt.plot(t,X_odeint)
plt.legend(["Predator", "Prey"])
plt.xlabel('Time', size=12)
plt.ylabel('Population', size=12)
plt.title('Lotka-Volterra predator-prey system with k2=0.8 & r=0.007', size=10)

#%%
#k2=.8, r = .5
xe, ye, Vectordxdt, Vectordydt = Phase_Portrait(k1, 0.8, d1, d2, 0.5, y0)
plt.subplot(2,4,1)
plt.quiver(xe, ye, Vectordxdt, Vectordydt)
plt.title('Phase Portrait for the Lotka-Volterra predator-prey system with k2=0.8 & r=0.5', size=8)
plt.xlabel('Predator', size=12)
plt.ylabel('Prey', size=12)
plt.streamplot(xe, ye, Vectordxdt, Vectordydt)
plt.xlim(0,50)
plt.ylim(0,50)
t, X_odeint = Odeint(k1, 0.8, d1, d2, 0.5, y0, xi, yi, Ti, Tf, dt)
plt.subplot(2,4,5)
plt.plot(t,X_odeint)
plt.legend(["Predator", "Prey"])
plt.xlabel('Time', size=12)
plt.ylabel('Population', size=12)
plt.title('Lotka-Volterra predator-prey system with k2=0.8 & r=0.5', size=10)
#k2=.8, r = 1
xe, ye, Vectordxdt, Vectordydt = Phase_Portrait(k1, 0.8, d1, d2, 1.0, y0)
plt.subplot(2,4,2)
plt.quiver(xe, ye, Vectordxdt, Vectordydt)
plt.title('Phase Portrait for the Lotka-Volterra predator-prey system with k2=0.8 & r=1.0', size=8)
plt.xlabel('Predator', size=12)
plt.ylabel('Prey', size=12)
plt.streamplot(xe, ye, Vectordxdt, Vectordydt)
plt.xlim(0,50)
plt.ylim(0,50)
t, X_odeint = Odeint(k1, 0.8, d1, d2, 1.0, y0, xi, yi, Ti, Tf, dt)
plt.subplot(2,4,6)
plt.plot(t,X_odeint)
plt.legend(["Predator", "Prey"])
plt.xlabel('Time', size=12)
plt.ylabel('Population', size=12)
plt.title('Lotka-Volterra predator-prey system with k2=0.8 & r=1.0', size=10)
#k2=.8, r = 1.5
xe, ye, Vectordxdt, Vectordydt = Phase_Portrait(k1, 0.8, d1, d2, 1.5, y0)
plt.subplot(2,4,3)
plt.quiver(xe, ye, Vectordxdt, Vectordydt)
plt.title('Phase Portrait for the Lotka-Volterra predator-prey system with k2=0.8 & r=1.5', size=8)
plt.xlabel('Predator', size=12)
plt.ylabel('Prey', size=12)
plt.streamplot(xe, ye, Vectordxdt, Vectordydt)
plt.xlim(0,50)
plt.ylim(0,50)
t, X_odeint = Odeint(k1, 0.8, d1, d2, 1.5, y0, xi, yi, Ti, Tf, dt)
plt.subplot(2,4,7)
plt.plot(t,X_odeint)
plt.legend(["Predator", "Prey"])
plt.xlabel('Time', size=12)
plt.ylabel('Population', size=12)
plt.title('Lotka-Volterra predator-prey system with k2=0.8 & r=1.5', size=10)
#k2=.8, r=2
xe, ye, Vectordxdt, Vectordydt = Phase_Portrait(k1, 0.8, d1, d2, 2.0, y0)
plt.subplot(2,4,4)
plt.quiver(xe, ye, Vectordxdt, Vectordydt)
plt.title('Phase Portrait for the Lotka-Volterra predator-prey system with k2=0.8 & r=2.0', size=8)
plt.xlabel('Predator', size=12)
plt.ylabel('Prey', size=12)
plt.streamplot(xe, ye, Vectordxdt, Vectordydt)
plt.xlim(0,50)
plt.ylim(0,50)
t, X_odeint = Odeint(k1, 0.8, d1, d2, 2.0, y0, xi, yi, Ti, Tf, dt)
plt.subplot(2,4,8)
plt.plot(t,X_odeint)
plt.legend(["Predator", "Prey"])
plt.xlabel('Time', size=12)
plt.ylabel('Population', size=12)
plt.title('Lotka-Volterra predator-prey system with k2=0.8 & r=2.0', size=10)

#%%
#k2=.8, r=2.5
xe, ye, Vectordxdt, Vectordydt = Phase_Portrait(k1, 0.8, d1, d2, 2.5, y0)
plt.subplot(2,4,4)
plt.quiver(xe, ye, Vectordxdt, Vectordydt)
plt.title('Phase Portrait for the Lotka-Volterra predator-prey system with k2=0.8 & r=2.5', size=8)
plt.xlabel('Predator', size=12)
plt.ylabel('Prey', size=12)
plt.streamplot(xe, ye, Vectordxdt, Vectordydt)
plt.xlim(0,50)
plt.ylim(0,50)
t, X_odeint = Odeint(k1, 0.8, d1, d2, 2.5, y0, xi, yi, Ti, Tf, dt)
plt.subplot(2,4,8)
plt.plot(t,X_odeint)
plt.legend(["Predator", "Prey"])
plt.xlabel('Time', size=12)
plt.ylabel('Population', size=12)
plt.title('Lotka-Volterra predator-prey system with k2=0.8 & r=2.5', size=10)




#%%
#Verification of the Model
plt.figure()
#r=1.4
t, X_odeint = Odeint(k1, k2, d1, d2, 2, y0, xi, yi, Ti, Tf, dt)
plt.subplot(2,4,1)
plt.plot(t,X_odeint)
plt.legend(["Predator", "Prey"])
plt.xlabel('Time', size=12)
plt.ylabel('Population', size=12)
plt.title('Lotka-Volterra predator-prey system with r=1.4', size=14)
#d1=100
t, X_odeint = Odeint(k1, k2, 100, d2, r, y0, xi, yi, Ti, Tf, dt)
plt.subplot(2,4,2)
plt.plot(t,X_odeint)
plt.legend(["Predator", "Prey"])
plt.xlabel('Time', size=12)
plt.ylabel('Population', size=12)
plt.title('Lotka-Volterra predator-prey system with d1=100', size=14)
#d2=100
t, X_odeint = Odeint(k1, k2, d1, 100, r, y0, xi, yi, Ti, Tf, dt)
plt.subplot(2,4,3)
plt.plot(t,X_odeint)
plt.legend(["Predator", "Prey"])
plt.xlabel('Time', size=12)
plt.ylabel('Population', size=12)
plt.title('Lotka-Volterra predator-prey system with d2=100', size=14)
#xi=40
t, X_odeint = Odeint(k1, k2, d1, d2, r, y0, 40, yi, Ti, Tf, dt)
plt.subplot(2,4,4)
plt.plot(t,X_odeint)
plt.legend(["Predator", "Prey"])
plt.xlabel('Time', size=12)
plt.ylabel('Population', size=12)
plt.title('Lotka-Volterra predator-prey system with xi=40', size=14)
#yi=40
t, X_odeint = Odeint(k1, k2, d1, d2, r, y0, xi, 40, Ti, Tf, dt)
plt.subplot(2,4,5)
plt.plot(t,X_odeint)
plt.legend(["Predator", "Prey"])
plt.xlabel('Time', size=12)
plt.ylabel('Population', size=12)
plt.title('Lotka-Volterra predator-prey system with yi=40', size=14)
#k2=.1
t, X_odeint = Odeint(k1, .1, d1, d2, r, y0, xi, yi, Ti, Tf, dt)
plt.subplot(2,4,6)
plt.plot(t,X_odeint)
plt.legend(["Predator", "Prey"])
plt.xlabel('Time', size=12)
plt.ylabel('Population', size=12)
plt.title('Lotka-Volterra predator-prey system with k2=.1', size=14)
#k1=.02
t, X_odeint = Odeint(.02, k2, d1, d2, r, y0, xi, yi, Ti, Tf, dt)
plt.subplot(2,4,7)
plt.plot(t,X_odeint)
plt.legend(["Predator", "Prey"])
plt.xlabel('Time', size=12)
plt.ylabel('Population', size=12)
plt.title('Lotka-Volterra predator-prey system with k1=.02', size=14)